add postgresql.conf from outside into the database container
status-im/infra-role-postgres-ha pull request #7
Opened 2024-06-20 19:17 UTC by Ivansete-status

We are starting to control-version the changes of the postgres config file.

Notice that this initial file has been extracted from the current `store-db-01.do-ams3.shards.staging` node.

I only added some parameters, commented, that will be useful for us to debug the database. To find those new parameters just look for the 'waku' word within the postgresql.conf file.

2024-06-24 07:51 UTC, jakubgs commented on templates/postgresql.conf
> +# -----------------------------
This whole config file is mostly noise. I don't think it's a good idea to commit it like this. Nor does committing it like this help us in any way, since it doesn't allow us to customize the settings.

If you get rid of comments and empty lines this file is nothing but this:
```
listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB
log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'
```
Which is a bit lines than 817 lines of noise.

Lets make this file an actual template and generate values from a dict variable that can be overriden. Even better if there's defaults dict too.

2024-06-24 07:52 UTC, jakubgs commented on templates/docker-compose.yml.j2
> +      -p {{ postgres_ha_cont_port }} -c config_file=/var/lib/postgresql/data/postgresql.conf
```suggestion
      -p {{ postgres_ha_cont_port }}
      -c config_file=/var/lib/postgresql/data/postgresql.conf
```

2024-06-24 07:52 UTC, jakubgs commented on tasks/config.yml
> +    - 'templates/postgresql.conf'
What is the point of this `with_fileglob`? Also you're not using `postgres_ha_postgres_config_file` for anything.

2024-06-24 07:54 UTC, jakubgs requested changes
This doesn't make things confgurable.

Also the commit title needs work. Missing prefix and unnecessary information like "into the database container". What would make more sense would be something like:
```
config: add postgres db config template
```

2024-06-25 13:16 UTC, jakubgs commented on templates/postgresql.conf
> +listen_addresses = '*'
This is not what I meant. This config is still not overwriteable in any way. We need a variable for this.

2024-06-25 13:23 UTC, Ivansete-status commented
I'm closing and reopening from an "origin" branch and not from a forked repo

2024-06-25 13:23 UTC, closed without merging